name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build and Deploy
        run: |
          # Initialize and switch to the gh-pages branch
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git fetch origin
          git checkout gh-pages || git checkout --orphan gh-pages
          git reset --hard

          # Copy the static content to the gh-pages branch
          cp -r * .  # Copy content to the current directory
          
          # Commit and push the changes to the gh-pages branch
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force origin gh-pages
